console.log("try and catch");
let a= 20
try {console.log("start the try and catch block");
//  let b=35
    console.log(b);
    console.log("try block end");
} catch (error) {
    // console.log("b is not defined");
    console.log(error);
}finally{
    console.log("error");
}
console.log(a);